 MBTN_LEFT        cycle pause         #event: click
 MBTN_LEFT        cycle fullscreen    #event: double_click
 MBTN_LEFT_DBL    ignore
 MBTN_RIGHT       script-binding uosc/menu
 RIGHT            seek  5
 LEFT             seek -5
 UP               seek -1 exact
 DOWN             seek  1 exact
 q                quit
 ESC              set fullscreen no
 ENTER            set fullscreen yes
 .                frame-step
 ,                frame-back-step
 SPACE            cycle pause
 z                add sub-delay -0.1
 x                add sub-delay  0.1
 s                screenshot
 S                screenshot video
 i                script-binding display-stats-toggle
