 script-opts-append = uosc-video_types=avi,flv,m2ts,m4v,mkv,mov,mp4,mpeg,mpg,ogv,rm,rmvb,ts,vob,webm,wmv
 script-opts-append = uosc-audio_types=aac,ac3,ape,dsf,dts,flac,m4a,mka,mp3,ogg,opus,wav,wma,wv
 script-opts-append = uosc-image_types=apng,avif,bmp,gif,jfif,jpeg,jpg,jxl,png,svg,tif,tiff,webp
 script-opts-append = uosc-subtitle_types=ass,idx,lrc,mks,pgs,sup,srt,ssa,txt,vtt
 script-opts-append = uosc-default_directory={drives}
 script-opts-append = uosc-languages=zh-hans
